[package]
name = "libui"
version = "0.5.1"
edition = "2021"
description = "User interface mock-up and demo for Rend3/Egui game-type cross platform applications"


# Usable targets:
# native (on Linux)
# x86_64-pc-windows-gnu

[package.metadata.bundle]
identifier = "com.animats.ui-mock"
category = "Game"
resources = ["src/images"]
icon = ["src/images/64x64.png", "src/images/32x32.png"]

[features]
#   Replay file is a development feature and will be off for production
default = ["replay"]
#   Feature "tracy" enables profiing with Tracy
tracy = ["tracy-client", "profiling/profile-with-tracy"]
#   Feature "replay" enables saving and reloading the viewer state.
#   This should not be enabled in production builds for content security.
replay = []

#   UDP replayer - replays UDP captures and outputs a huge JSON file
#   which can be displayed by another program

[[example]]
name = "ui-mock"
path = "src/examples/ui-mock/main.rs"

[dependencies]
glam = {version = "0.21.2", features = ["bytemuck", "serde"]}	
rend3 = { git = 'https://github.com/BVE-Reborn/rend3.git', rev = "a972b0ff0a98bb79b2b1c8812e3a823840a5e02e" }
rend3-routine = { git = 'https://github.com/BVE-Reborn/rend3.git', rev = "a972b0ff0a98bb79b2b1c8812e3a823840a5e02e"}
rend3-gltf = { git = 'https://github.com/BVE-Reborn/rend3.git', rev = "a972b0ff0a98bb79b2b1c8812e3a823840a5e02e" }
rend3-framework = { git = 'https://github.com/BVE-Reborn/rend3.git', rev = "a972b0ff0a98bb79b2b1c8812e3a823840a5e02e" }

# Egui renderer integration
rend3-egui = { git = 'https://github.com/BVE-Reborn/rend3.git', rev = "a972b0ff0a98bb79b2b1c8812e3a823840a5e02e" }

# The egui immediate mode gui library
egui = "0.18.1"
####egui = "0.19.0" ## ***NOTYET*** rend3 integration
# Winit integration with egui
egui_winit_platform = "0.15.0"
# logging
#### env_logger = { version = "0.9", default-features = false, features = ["termcolor", "atty"] }			
# Importing png's
image = { version = "0.23.14", default-features = false, features = ["png"] }
# Portable implementation of Instant.
instant = { version = "0.1", features = ["wasm-bindgen"] }

# winit = "0.26.1"
# Windowing
winit = "0.26"
# Opening URL's
webbrowser = "0.5.5"
# Creating textures
wgpu = "0.13"
# File dialogs
rfd = "0.8.3"
futures = "0.3.21"
raw-window-handle = "0.4.3"
# Internationalization
once_cell = "1.12.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
sys-locale = "0.2.0"
oxilangtag = "0.1.3"
# Dark mode
dark-light = "0.2.3"
# Preferences
directories = "4.0"
# Performance monitoring
tracy-client = {version = "0.13", optional = true }
profiling = { version = "^1.0.6", default-features = false }
# System information
sysinfo = { version = "0.24", default-features = false }
# Concurrency
crossbeam-channel = "0.5"
# Error handling
log = "0.4.17"
simplelog = "0.10.0"
anyhow = "1.0"
# Security
md5 = "0.7.0"
zeroize = {version = "1.5.7", features = ["zeroize_derive"]}
keyring = "1.2.0"
hex = "0.4.2"
